# Build workflow that runs tests
name: Tests

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore src\

    - name: Build
      run: dotnet build src\

    - name: Test
      run: dotnet test src\

